name = "blockless-nextjs-tutorial"
version = "1.0.0"
type = "site"
content_type = "html"

[deployment]
permission = "private"
nodes = 4

[build]
dir = ".bls"
public_dir = "out"
entry = "blockless-nextjs-tutorial_debug.wasm"
command = ""

[build_release]
dir = ".bls"
public_dir = "out"
entry = "blockless-nextjs-tutorial.wasm"
command = ""
